### ISSUE TITLE
TintProgressBar不显示

### ISSUE THREAD

**Issue by liaosiyang** [Bilibili/MagicaSakura#1]
我在新建的App里使用TintProgressBar时设置了app:progressIndeterminateTint="@color/theme_color_primary"
时就显示不出来这个TintProgressBar了，不设置这个属性的时候才可以显示。

**Comment by xyczero** [comment]
代码能贴出来看一下吗？还有机型和系统版本

**Comment by liaosiyang** [comment]
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <com.bilibili.magicasakura.widgets.TintProgressBar
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:indeterminate="true"
            app:progressIndeterminateTint="@color/theme_color_primary"/>

        <com.bilibili.magicasakura.widgets.TintProgressBar
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:indeterminate="true" />
    </LinearLayout>

上面的TintProgressBar不显示，下面的可以，我新建了一个工程测试了的：https://github.com/liaosiyang/MyApplication

**Comment by xyczero** [comment]
项目中的Application里面没有实现ThemeUtils的switchColor接口，所以TintProgressBar没取到颜色，已提交新的pr到demo项目中了

**Comment by liaosiyang** [comment]
额 是我蠢了 我Application里面的replaceColor方法没重写，直接返回0了，所以颜色是白色就显示不出来了
