### ISSUE TITLE
在sdk21版本及以上，无法支持ripple的主题颜色切换

### ISSUE THREAD

**Issue by pzl237** [Bilibili/MagicaSakura#11]
我使用的ripple如下：
<?xml version="1.0" encoding="utf-8"?>
<ripple xmlns:android="http://schemas.android.com/apk/res/android"
    android:color="@color/rippleColor">
    <item>
        <shape android:shape="rectangle">
            <corners android:radius="30dp" />
            <solid android:color="@color/DefaultColorNormal" />
        </shape>
    </item>
</ripple>

对应的selector如下（可用）：
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="false">
        <shape android:shape="rectangle">
            <corners android:radius="30dp" />
            <solid android:color="@color/DefaultColorNormal" />
        </shape>
    </item>
    <item android:state_pressed="true">
        <shape android:shape="rectangle">
            <corners android:radius="30dp" />
            <solid android:color="@color/rippleColor" />
        </shape>
    </item>
</selector>

**Comment by pzl237** [comment]
@xyczero   您好，ripple支持主题切换的有进展了没？ 主要还是涟漪效果没了。

**Comment by xyczero** [comment]
这周发布版本5.0及以上支持ripple染色

**Comment by pzl237** [comment]
@xyczero 非常期待，这样我项目就可以解决这个ripple问题了。

**Comment by xyczero** [comment]
请更新至0.1.3版本
