### ISSUE TITLE
在ListView上面使用出现item混乱

### ISSUE THREAD

**Issue by SkornZero** [Bilibili/MagicaSakura#12]
使用ListView的话，如果滑动到一定距离，有些item被复用的话，切换Theme，这时候ListView当前页面的item成功换色，但是再次滑动会出现被复用的换色前的item，请问这个问题如何解决的？

**Comment by xyczero** [comment]
目前只对RecyclerView进行了支持，后续会添加支持

**Comment by xyczero** [comment]
已经支持listview，版本升至0.1.4即可。

**Comment by SkornZero** [comment]
请问gridview也同时支持吗 ?

**Comment by xyczero** [comment]
支持的

**Comment by xyczero** [comment]
支持的
