### ISSUE TITLE
夜间模式

### ISSUE THREAD

**Issue by unknown92** [Bilibili/MagicaSakura#13]
您好，请问能不能补充说明一下夜间模式的使用步骤啊，或者在demo中加个夜间模式的例子，看了好几天还是没明白用您的这个library怎么处理一个模式设置不同控件变成不同颜色。

**Comment by xyczero** [comment]
夜间模式在README中有说明, 详细的可以看这篇博客文章的末尾 http://www.xyczero.com/blog/article/31/
