### ISSUE TITLE
gradle 无法同步

### ISSUE THREAD

**Issue by Sum41forever** [Bilibili/MagicaSakura#18]
Error:(2, 0) No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.
<a href="openFile:F:\AppSpace\MagicaSakura-master\**magicasakura\build.gradle**">

好像是这个 依赖打不开
apply plugin: 'com.github.dcendents.android-maven'

File</a>877b48d4afc0.png)

**Comment by Sum41forever** [comment]
![image](https://cloud.githubusercontent.com/assets/18468976/22057715/e6093646-dda0-11e6-8a9b-04f32c37e989.png)

**Comment by xyczero** [comment]
虽然版本有点老＝。＝，但我能同步到的哇
