### ISSUE TITLE
切换主题后的一些问题

### ISSUE THREAD

**Issue by Sum41forever** [Bilibili/MagicaSakura#19]
1. 八种颜色，第一种粉色，点击切换后没反应。其他的颜色切换都可以。
2. 切换了主题后 状态栏变色，但是进入下一个页面，状态栏又回到了原来的颜色。但是标题栏和控件是改变了的

我在基类的Activity里设置的监听切换，所有上下文都是同一个。

**Comment by xyczero** [comment]
1. 框架的自动染色切换是基于使用了框架中定制的TintXXX控件。
2. 状态栏的染色因android不同版本的差异以及不同的需求，需要自己去处理。
