### ISSUE TITLE
切换主题后TintImageView中的颜色没有改变，测试机型系统版本Android5.0

### ISSUE THREAD

**Issue by jlertele** [Bilibili/MagicaSakura#2]
AppCompatImageHelper ——>applySupportImageTint()方法需要去除版本号判断，直接  setImageDrawable(null);TintImageView的背景颜色方可同步更新。

**Comment by xyczero** [comment]
自测在5.0手机上运行正常，请问你是在项目demo中遇到无法变色情况，还是在自己的demo 中，如果是在自己demo中方便贴一下代码吗？

**Comment by leoliuzhou** [comment]
是在项目demo中遇到部分控件无法根据主题变色的情况，程序后台后再返回前台，控件颜色恢复正常。
bug请见图片链接：
http://o8ap2cw2n.bkt.clouddn.com/16-7-4/77150854.jpg
