### ISSUE TITLE
release版本编译阶段报错

### ISSUE THREAD

**Issue by fg2q1q3q** [Bilibili/MagicaSakura#27]
1、Warning:com.bilibili.magicasakura.widgets.TintGridLayout: can't find referenced method 'boolean isInEditMode()' in program class com.bilibili.magicasakura.widgets.TintGridLayout
已查到原因，建议增加混淆规则
2、希望能增加Switch控件支持

**Comment by xyczero** [comment]
已增加SwitchComat控件支持

**Comment by fg2q1q3q** [comment]
好的，感谢，辛苦啦
