### ISSUE TITLE
使用CoordinatorLayout，切换夜间模式后Glide加载的图片没有了

### ISSUE THREAD

**Issue by shaomeiqi** [Bilibili/MagicaSakura#39]
这是我的布局文件
如果直接设置本地图片不用Glide加载，切换后图片没有异常，但是用Glide加载，切换夜间模式后图片就没有了

<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <ImageView
                android:id="@+id/iv_logo_past_week"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="@dimen/x70"
                android:layout_marginRight="@dimen/x70"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:layout_marginTop="@dimen/x9"
                android:text="fdsafsdafassad"
                android:textColor="#aaa"
                android:textSize="@dimen/x13"/>

        </LinearLayout>

            <com.ajguan.library.EasyRefreshLayout
                android:id="@+id/refreshlayout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_behavior="@string/pageBehavior">

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/rv"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"/>

            </com.ajguan.library.EasyRefreshLayout>

</android.support.design.widget.CoordinatorLayout>

**Comment by xyczero** [comment]
那你需要看一下Glide的代码了

**Comment by shaomeiqi** [comment]
那天脑子抽风了。。。解析的时候根本就不会存下这种资源
