### ISSUE TITLE
在menu里该怎么给android:icon标签染色呢？

### ISSUE THREAD

**Issue by LvZhenDong** [Bilibili/MagicaSakura#4]
我用app:drawableTint="@color/theme_color_primary"没有效果
下面是我的代码
![code](https://cloud.githubusercontent.com/assets/18679785/17167780/787ead18-5411-11e6-9643-c88e57761e2d.png)

**Comment by xyczero** [comment]
可以修改，menu采用自定布局，在自定义布局中使用Tint控件即可，直接在<item></item>写是无法生效的。

**Comment by LvZhenDong** [comment]
哦，像哔哩哔哩里这个menu是用TintTextView之类的来实现的吗？
![screenshot_2016-07-28-17-49-50](https://cloud.githubusercontent.com/assets/18679785/17208989/942007ba-54ed-11e6-8025-4d0a45bec519.png)

**Comment by xyczero** [comment]
嗯，是的
