### ISSUE TITLE
请教EditText中设置tintBackgroud的问题

### ISSUE THREAD

**Issue by Caij** [Bilibili/MagicaSakura#40]
EditText中设置tintBackgroud对默认背景无法生效，需要和官方demo一样自己设置图片背景才会生效。 看了源码，没找到其中为什么不生效。（tintBackgroud默认背景在普通状态下生效，在选中状态下不生效）

**Comment by xyczero** [comment]
不能直接在xml中使用tintBackgroud属性，需要和drawable配合使用或者可以在java代码中直接染色

**Comment by Caij** [comment]
已经解决 谢谢
