### ISSUE TITLE
TintImageView app:imageTint在Gradle4.1（Android  Studio3.0）版本中有问题。

### ISSUE THREAD

**Issue by Caij** [Bilibili/MagicaSakura#41]
classpath 'com.android.tools.build:gradle:3.0.0'

打断点  发现app:imageTint 取不到值。

**Comment by Caij** [comment]
最终定位到Aapt2的问题 禁用掉就没问题。

**Comment by Caij** [comment]
https://issuetracker.google.com/issues/68688018  已经向google 反馈，官方建议不要使用硬编码， 需使用R中的变量

**Comment by xyczero** [comment]
不要方，马上适配

**Comment by xyczero** [comment]
升级至0.1.8版本即可

**Comment by Caij** [comment]
感谢

**Comment by xyczero** [comment]
应该的，欢迎继续提供意见哈。

**Comment by Caij** [comment]
0.1.8版本好像没发布成功

**Comment by xyczero** [comment]
再试试
