### ISSUE TITLE
自定义Tintable控件issue

### ISSUE THREAD

**Issue by qfxl** [Bilibili/MagicaSakura#43]
作者您好，在下准备写一个继承TabLayout并且实现Tintable接口时发现，AppCompatBackgroundHelper的loadFromAttribute不是public，希望作者能放开这个方法好让群众更加方便的去实现自己的Tintable控件，
阿里嘎多

**Comment by xyczero** [comment]
您好，您可以提pr上来，目前暂时不想对外暴露，暴露后升级或者更改策略就很被动

**Comment by qfxl** [comment]
emmm，好的，请问一下pr有格式要求吗？

**Comment by xyczero** [comment]
正常提交即可

**Comment by qfxl** [comment]
这就很尴尬了。。抱歉啊，哈哈哈

**Comment by xyczero** [comment]
😀  https://github.com/Bilibili/MagicaSakura/pull/44#issuecomment-346800920

**Comment by qfxl** [comment]
ok，谢谢，是在下理解错了。😂
