### ISSUE TITLE
ImageView 会崩溃  app:imageTint    app:imageTintMode 属性不能用吗

### ISSUE THREAD

**Issue by easyandroid** [Bilibili/MagicaSakura#46]
<com.bilibili.magicasakura.widgets.TintImageView
        android:id="@+id/tv_rv_item_icon"
        android:layout_width="30dp"
        android:layout_height="30dp"
        app:imageTint="@color/theme_color_img_transparent_bg"
        app:imageTintMode="multiply"
       />

**Comment by xyczero** [comment]
暂没有复现，你可以把崩溃的堆栈贴出来看下，还有机型，版本等

**Comment by easyandroid** [comment]
谢谢，我参考demo 了  。

**Comment by easyandroid** [comment]
谢谢，我参考demo 了 ，实现了 。不好意思哈
