### ISSUE TITLE
依赖方式compile 'com.bilibili:magicasakura:0.1.8@aar'会报错

### ISSUE THREAD

**Issue by Kanghanbin** [Bilibili/MagicaSakura#68]
大佬，麻烦更新下readme,我猜是0.1.8@aar版本有问题。
依赖方式导入compile 'com.bilibili:magicasakura:0.1.8@aar'，然后xml引入widget运行时会报错，找不到tintxxx类，下了个simaple，看到
version = "0.1.9-beta3"了，重新依赖新版本"com.bilibili:magicasakura:0.1.9-beta3"没问题。

**Comment by xyczero** [comment]
嗯，OK
