### ISSUE TITLE
请问如何自定义主题色

### ISSUE THREAD

**Issue by fg2q1q3q** [bilibili/MagicaSakura#69]
我看到示例中全都是xml中预设的主题色，请问能否动态设置任意主题色，比如通过服务器换肤的情况，java代码如何设置主题色

**Comment by fg2q1q3q** [comment]
经过大半天折腾，已经完整解决该问题，主要是调整application的两个重写方法，如果代码理解不全面的话很容易写漏或写错。

**Comment by xyczero** [comment]
🤗🤗🤗
