### ISSUE TITLE
夜间模式

### ISSUE THREAD

**Issue by Saxxhw** [Bilibili/MagicaSakura#7]
您好，请问哔哩哔哩动画中的夜间模式是怎么实现的？我在demo里做了修改，但是只是改变了toolbar、文字等控件的颜色，界面的背景色还是白色的。

**Comment by xyczero** [comment]
简单说就是在res目录下建立相应的xxx-night资源文件夹，同时在java代码中通过resource的configuration进行切换即可，具体你可以看这篇文章http://www.xyczero.com/blog/article/29/

**Comment by Saxxhw** [comment]
多谢指点！
